### PR TITLE
Initial import

### PR DESCRIPTION
**Pull request by alex-fedorov**
This PR creates initial foundation for `docker-compose` running inside of `docker` image.

### CODE REVIEW

**Comment by alaa** [comment]
LGTM, just one side note: I would define the `commit sha` in a env variable and use it as reference in the URL.

**Comment by alex-fedorov** [comment]
@alaa Done.

**Comment by alex-fedorov** [comment]
Thanks!

**Comment by widmogrod** [comment]
@alex-fedorov  Where do we need docker-compose inside of the docker? And what is the reason to have one?

**Comment by alex-fedorov** [comment]
@widmogrod Here: https://github.com/brainly/srv-content-bot/pull/44 - Together with @alaa we came to conclusion that most non-intrusive way is to run `docker-compose@1.5dev` would be in docker container on CI server.

**Pull request merged**
